# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (6)
# #########################################################################

class CategoricalAttributes(BaseModel):
    type1: typing.Optional[types.PokemonType] = None
    type2: typing.Optional[types.PokemonType] = None
    generation: typing.Optional[int] = None
    is_legendary: typing.Optional[bool] = None
    is_mythical: typing.Optional[bool] = None
    is_starter: typing.Optional[bool] = None
    evolution_stage: typing.Optional[types.EvolutionStage] = None

class ColorDistribution(BaseModel):
    primary: typing.Optional[types.PokemonColor] = None
    secondary: typing.Optional[types.PokemonColor] = None
    accent: typing.Optional[types.PokemonColor] = None

class ParsedPromptAttributes(BaseModel):
    type1: typing.Optional[types.PokemonType] = None
    type2: typing.Optional[types.PokemonType] = None
    primary_color: typing.Optional[types.PokemonColor] = None
    secondary_color: typing.Optional[types.PokemonColor] = None
    body_shape: typing.Optional[types.BodyShape] = None
    size_class: typing.Optional[types.SizeClass] = None
    evolution_stage: typing.Optional[types.EvolutionStage] = None
    habitat: typing.Optional[types.Habitat] = None
    is_legendary: typing.Optional[bool] = None
    is_mythical: typing.Optional[bool] = None

class PokemonMetadata(BaseModel):
    prompts: typing.List[str]
    visual_attributes: typing.Optional["VisualAttributes"] = None
    categorical_attributes: typing.Optional["CategoricalAttributes"] = None
    semantic_attributes: typing.Optional["SemanticAttributes"] = None

class SemanticAttributes(BaseModel):
    personality_traits: typing.List[str]
    habitat: typing.Optional[types.Habitat] = None
    rarity: typing.Optional[str] = None
    combat_style: typing.Optional[str] = None

class VisualAttributes(BaseModel):
    primary_colors: typing.List[types.PokemonColor]
    secondary_colors: typing.List[types.PokemonColor]
    color_distribution: typing.Optional["ColorDistribution"] = None
    body_shape: typing.Optional[types.BodyShape] = None
    size_class: typing.Optional[types.SizeClass] = None
    distinctive_features: typing.List[str]

# #########################################################################
# Generated type aliases (0)
# #########################################################################
