# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (6)
# #########################################################################

class BodyShape(str, Enum):
    Bipedal = "Bipedal"
    Quadruped = "Quadruped"
    Serpentine = "Serpentine"
    Winged = "Winged"
    Amorphous = "Amorphous"
    Insectoid = "Insectoid"
    Aquatic = "Aquatic"
    Humanoid = "Humanoid"

class EvolutionStage(str, Enum):
    Basic = "Basic"
    Middle = "Middle"
    Final = "Final"
    Single = "Single"
    Mega = "Mega"
    Gigantamax = "Gigantamax"

class Habitat(str, Enum):
    Forest = "Forest"
    Grassland = "Grassland"
    Mountain = "Mountain"
    Cave = "Cave"
    Sea = "Sea"
    Urban = "Urban"
    Rare = "Rare"
    Desert = "Desert"
    Tundra = "Tundra"
    Wetland = "Wetland"

class PokemonColor(str, Enum):
    Red = "Red"
    Blue = "Blue"
    Yellow = "Yellow"
    Green = "Green"
    Purple = "Purple"
    Orange = "Orange"
    Pink = "Pink"
    Brown = "Brown"
    Black = "Black"
    White = "White"
    Gray = "Gray"

class PokemonType(str, Enum):
    Normal = "Normal"
    Fire = "Fire"
    Water = "Water"
    Electric = "Electric"
    Grass = "Grass"
    Ice = "Ice"
    Fighting = "Fighting"
    Poison = "Poison"
    Ground = "Ground"
    Flying = "Flying"
    Psychic = "Psychic"
    Bug = "Bug"
    Rock = "Rock"
    Ghost = "Ghost"
    Dragon = "Dragon"
    Dark = "Dark"
    Steel = "Steel"
    Fairy = "Fairy"

class SizeClass(str, Enum):
    Tiny = "Tiny"
    Small = "Small"
    Medium = "Medium"
    Large = "Large"
    Huge = "Huge"

# #########################################################################
# Generated classes (6)
# #########################################################################

class CategoricalAttributes(BaseModel):
    type1: PokemonType
    type2: typing.Optional[PokemonType] = None
    generation: int
    is_legendary: bool
    is_mythical: bool
    is_starter: bool
    evolution_stage: EvolutionStage

class ColorDistribution(BaseModel):
    primary: PokemonColor
    secondary: typing.Optional[PokemonColor] = None
    accent: typing.Optional[PokemonColor] = None

class ParsedPromptAttributes(BaseModel):
    type1: PokemonType
    type2: typing.Optional[PokemonType] = None
    primary_color: PokemonColor
    secondary_color: typing.Optional[PokemonColor] = None
    body_shape: BodyShape
    size_class: SizeClass
    evolution_stage: EvolutionStage
    habitat: Habitat
    is_legendary: bool
    is_mythical: bool

class PokemonMetadata(BaseModel):
    prompts: typing.List[str]
    visual_attributes: "VisualAttributes"
    categorical_attributes: "CategoricalAttributes"
    semantic_attributes: "SemanticAttributes"

class SemanticAttributes(BaseModel):
    personality_traits: typing.List[str]
    habitat: Habitat
    rarity: str
    combat_style: str

class VisualAttributes(BaseModel):
    primary_colors: typing.List[PokemonColor]
    secondary_colors: typing.List[PokemonColor]
    color_distribution: "ColorDistribution"
    body_shape: BodyShape
    size_class: SizeClass
    distinctive_features: typing.List[str]

# #########################################################################
# Generated type aliases (0)
# #########################################################################
