# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.CategoricalAttributes": types.CategoricalAttributes,
    "stream_types.CategoricalAttributes": stream_types.CategoricalAttributes,

    "types.ColorDistribution": types.ColorDistribution,
    "stream_types.ColorDistribution": stream_types.ColorDistribution,

    "types.ParsedPromptAttributes": types.ParsedPromptAttributes,
    "stream_types.ParsedPromptAttributes": stream_types.ParsedPromptAttributes,

    "types.PokemonMetadata": types.PokemonMetadata,
    "stream_types.PokemonMetadata": stream_types.PokemonMetadata,

    "types.SemanticAttributes": types.SemanticAttributes,
    "stream_types.SemanticAttributes": stream_types.SemanticAttributes,

    "types.VisualAttributes": types.VisualAttributes,
    "stream_types.VisualAttributes": stream_types.VisualAttributes,


    "types.BodyShape": types.BodyShape,

    "types.EvolutionStage": types.EvolutionStage,

    "types.Habitat": types.Habitat,

    "types.PokemonColor": types.PokemonColor,

    "types.PokemonType": types.PokemonType,

    "types.SizeClass": types.SizeClass,

}